# Generated by Django 4.2.2 on 2023-06-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMgt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Level',
        ),
    ]
