# Generated by Django 4.2.2 on 2023-06-24 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMgt', '0002_rename_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admin_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 12, 13, 23, 270236)),
        ),
    ]
