# Generated by Django 4.2.2 on 2023-06-25 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMgt', '0003_alter_student_admin_no_alter_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 18, 52, 47, 647727)),
        ),
    ]
